### ISSUE TITLE
Why is the HPKE public XORed with the packet Length field?

### ISSUE THREAD

**Issue by DavidSchinazi** [martinduke/quic-version-aliasing#18]
draft-duke-quic-protected-initial-00 XORs the HPKE public key with the long header Length field, but doesn't explain why. What's the purpose of this? It sounds like it allows the server to detect mismatched keys without trying to decrypt the initial, but it isn't clear to me that this is a desirable feature.

**Comment by martinduke** [comment]
yes, that is exactly the purpose. For normal operation, this is strictly nice-to-have. When in Retry mode, however, it allows the server to send a Retry that the client can actually understand -- if the keys don't match, it's going to have to revert to v1, get another Initial, and then send Retry.

Otherwise we can't authenticate Retry the way this envisions.

**Comment by DavidSchinazi** [comment]
I'm not sure I understand what you meant by "it allows the server to send a Retry that the client can actually understand". Doesn't the server need the keys to match in order to derive the shared_secret which is required for the Retry Integrity Tag?

**Comment by martinduke** [comment]
Yes -- so if the keys don't match, the server sends VN, because the Retry Integrity check would fail.

**Comment by DavidSchinazi** [comment]
I see. So this allows the server to skip the (symmetric AES-GCM) initial decryption to find out whether the ECHO keys are correct. But the server has already had to perform the (asymmetric HPKE) decryption to derive shared_secret. Since asymmetric is generally orders of magnitude more CPU-expensive than symmetric, I'm not sure if this extra complexity is worth it.

**Comment by martinduke** [comment]
Ah, you've called attention to a typo. Section 9 says it's taken from the shared secret, whereas Section 7 and 8 say it's the public key. The latter is correct. There is no crypto operation.

Using the shared secret would reveal 62 bits of the shared secret!

**Comment by martinduke** [comment]
So there are two separate design decisions here:

Detect key mismatch by
(1) This packet length thing
(2) Trial Decrypt

Send Retry with
(A) a fixed integrity tag key
(B) One derived from shared_secret

In #17 you make a compelling case for (B) being quite expensive. If we were to end up doing (B) anyway, (2) seems like a trivial expense.

However, if we choose (A), Retries are cheap. We can't send a Retry without checking for key mismatch, because then if the keys we send Retry followed by a VN, which is bad. We must check for key mismatch before sending either VN or Retry, and it would be nice to not do a trial decrypt.

IMO the best equilibria are (1A) and (2B). (1A) has cheap retries; (2b) has secure (but very expensive) ones. The draft currently has (1B), which has expensive, secure retries but also the complex mechanism that saves very little except in the corner case where we send VN.
